version: "3"
services:
  react-app:
    image: react-app
    ports: 
      - "8000:8000"
    networks:
      - mern-app
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
  api-server:
    image: api-server
    ports:
      - "3000:3000"
    networks:
      - mern-app
    depends_on:
      - mongo
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local